Update to PureScript v0.15.0
purescript-node/purescript-node-fs pull request #59
Opened 2022-03-22 22:39 UTC by sigma-andex

**Description of the change**

Backlinking to purescript/purescript#4244

Migrates FFI to ES modules

---

**Checklist:**

- [x] Added the change to the changelog's "Unreleased" section with a reference to this PR (e.g. "- Made a change (#0000)")
- [x] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

2022-03-22 22:40 UTC, sigma-andex commented
🏓 @thomashoneyman @JordanMartinez

2022-03-22 22:59 UTC, JordanMartinez requested changes
Looks good, but it seems we're missing a changelog entry.

2022-03-22 22:59 UTC, JordanMartinez commented
CI is failing due to unused imports.

2022-03-23 00:24 UTC, thomashoneyman commented on src/Node/FS/Async.purs
> +foreign import close_ :: Fn2 FileDescriptor (JSCallback Unit) Unit
We can keep this as-is, but typically we'd name this

```purs
foreign import closeImpl :: ...
```

where `*Impl` denotes an FFI implementation

2022-03-23 00:25 UTC, thomashoneyman commented on src/Node/FS/Async.purs
> +foreign import close_ :: Fn2 FileDescriptor (JSCallback Unit) Unit
Admittedly, this library already diverged from our typical best practices with this big `fs` record 😆

2022-03-23 00:29 UTC, thomashoneyman approved these changes

2022-03-23 11:23 UTC, JordanMartinez approved these changes

2022-03-23 11:23 UTC, merged